version: "3"
services: 
  hub:
    image: selenium/hub:latest
    ports: 
      - "4444:4444"


  chrome:
    image: selenium/node-chrome:latest
    depends_on: 
      - hub
    environment: 
      - HUB_HOST=hub

#   Below volumn command resolves the tab crash issue in linux system     
    volumes:
      - /dev/shm:/dev/shm


  firefox:
    image: selenium/node-firefox:latest
    depends_on: 
      - hub
    environment: 
      - HUB_HOST=hub


  bdd:
    image: icemeetscoke/uiautomation
    depends_on: 
      - chrome
      - firefox
    environment: 
      - HUB_HOST=hub
    volumes: 
      -  C:\Users\ryanchen\WorkSpaces\LogixPanel\test-result:/usr/share/automation/target/html


  